name: Backend CI

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        if: ${{ hashFiles('backend/pom.xml') != '' }}
        working-directory: backend
        run: mvn -B -DskipTests package